### ISSUE TITLE
Obs freezes after installation

### ISSUE THREAD

**Issue by neetch1** [Xaymar/obs-stream-effects#83] opened 2019-10-29 16:30 UTC
#57 # Description
Obs freezes after installing obs-stream-effects as seen in this screenshot:
https://prnt.sc/ppqbvm

### System Information

- Operating System: Windows 10 64 bit
- CPU: 4790k
- GPU: gtx970
- RAM: 8gb

If you need more info let me know thanks

**Comment by neetch1** [comment] 2019-10-29 17:13
Nevermind 7.0 works without problems thx alot for this plugin much appreciated

**Comment by neetch1** [comment] 2019-10-29 19:48
The same freezing error just started happening for the older versions as well ...  it seems to work fine right after install but after 10min it freezes and then after it happens the first time, every time you open the program after it will be frozen from the start hmm

**Comment by neetch1** [comment] 2019-10-31 23:51
Any idea what could cause this?

**Comment by Xaymar** [comment] 2019-11-01 07:48
Not really, no. Even log files would likely not help figure this out. Only thing I can think of is that you have some sort of circular reference going on (Scene A in Scene B, Scene B in Scene A) and it causes a permanent loop.

**Comment by neetch1** [comment] 2019-11-01 14:58
I do have a very messy setup will try cleaning it up and see if it helps thanks

**Comment by neetch1** [comment] 2019-11-01 18:07
Ah i found the source of the problem. Everytime i add blur effect, gaussian and directional blur and then press ok, obs freezes. It doesnt matter if i have a completely blank obs with only 1 scene.

Here's the logs if they are of any use: https://pastebin.com/Gf9qNjDc

There seems to be no problem when messing with any of the other effects.

**Comment by Xaymar** [comment] 2019-12-16 22:12
I can not confirm this behavior in the current latest beta/pre-release, or in the last full release.

**Comment by neetch1** [comment] 2019-12-17 21:37
its fixed? nice. will let you know if i still got the problem once trying new update

**Comment by Xaymar** [comment] 2019-12-17 22:48
I seem to have reproduced it by pure chance. Since there were no repro steps provided, it's likely that this is a bug that happens 1 in 1000 times and is then always repeatable with the same setup.

**Comment by Xaymar** [comment] 2019-12-17 22:51
Bug confirmed to be caused by Gaussian blur set to Directional. There is a left over `obs_enter_graphics` call that is not matched by any `obs_leave_graphics` call(s). Fixed in master.

**Closed** 2019-12-17 22:53 UTC
Labels: status:confirmed, type:bug/crash
