### ISSUE TITLE
obs-stream-effects-0.4.2.215 is not showing at the filters menu

### ISSUE THREAD

**Issue by MisterPiBody** [Xaymar/obs-stream-effects#46] opened 2019-02-02 19:01 UTC
As title says

I've downloaded obs-stream-effects-0.4.2.215.7z, copy/paste it above the previous version i had, launched obs, select the source, hit filters, none of effects exist there. 
Currently I've rolled back to the one i've used (0.4.0) which is working as for me right

**Comment by Xaymar** [comment] 2019-02-02 19:07
Please upload a log file.

**Comment by MisterPiBody** [comment] 2019-02-02 19:20
[https://drive.google.com/open?id=1bSnbmkpGieYFKG6vLWR2j3hJfUL0oJX0](url)

Sorry, not a github user, so don't know how to do things correctly here

**Comment by MisterPiBody** [comment] 2019-02-03 04:50
I don't know if i should make another topic or continue here
As i wrote at my last post - things were streched wrong when im using 3D Transform. As soon as i change at least one parameter in this filter, everything become normal, but after each OBS restart - it's all the mess again. Here some pictures of what im talking about:
Filter was just applied
![before](https://user-images.githubusercontent.com/30563522/52172808-3f25fb00-2788-11e9-8e13-0fa2fca976a5.jpg)
After OBS restart
![after](https://user-images.githubusercontent.com/30563522/52172809-4220eb80-2788-11e9-92a1-3e19a23af624.jpg)

**Comment by Xaymar** [comment] 2019-02-10 11:57
Unfortunately I have been unable to reproduce that error. There have been two reports of this so far.

**Comment by sendblink23** [comment] 2019-02-14 15:00
@Xaymar  Are you going to fix that Stretching issue? For me the current version 0.4.2.215 causes it for me on both OBS Studio 22.0.2 and beta OBS Studio RC2 23.0.0-rc2.  Only using the older version 0.4.2 I don't have that issue on both.

**Comment by Xaymar** [comment] 2019-02-14 15:10
@sendblink23 As stated 4 days ago, I am unable to get it to happen. I have tried most sources, but my current guess is that async sources (Browser Source, Media Source, Video Capture Source) are the cause.

Fixing it is just a matter of if I can reproduce the bug.

**Comment by sendblink23** [comment] 2019-02-14 15:30
@sendblink23   do you want to Team Viewer and do the process on my computer of you installing OBS and adding your plugin ... and reproduce it that way so you can check from my pc what is happening? And yes I can confirm with Video Capture and Browser source being affected since that is where I see it happening I mean its where I use the 3d effects on. Let me know how to send you the Team Viewer details if you want to do this.

**Comment by Xaymar** [comment] 2019-02-14 15:33
@sendblink23 Just a video or text steps of how to get the bug to happen (for example what website in a Browser Source causes it) would be enough.

**Comment by sendblink23** [comment] 2019-02-14 15:37
@Xaymar   alright I will record the entire process of downloading and installing OBS and your latest plugin so its all clean, also adding your older version as well. I will use the beta with portable flag for this test recording.

**Comment by sendblink23** [comment] 2019-02-14 16:25
@Xaymar  
Here you go, video screen recording of clean install OBS Studio RC2 beta + install of Stream Effect 0.4.2.215 then showing the stretch bug with 3d effect on Video Capture and Browser sources with closing and reopening OBS.
https://youtu.be/5mudkZj4akQ

And here video screen recording of installing of OBS Studio RC2 beta + install of the older Stream Effect 0.4.2 then showing that older version working all fine the 3d effect with closing and reopening OBS.
https://youtu.be/5YL0ECtj2u0

**Comment by Xaymar** [comment] 2019-02-15 12:34
Reproduced and filed under #48.

**Closed** 2019-02-15 12:35 UTC
Labels: status:fixed
